<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Customer Statement</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
        .header h1 { margin: 0; font-size: 18px; color: #111; }
        .header p { margin: 2px 0; color: #666; }
        .kpis { margin-bottom: 20px; width: 100%; border-collapse: collapse; }
        .kpis td { padding: 10px; background: #f9f9f9; border: 1px solid #eee; text-align: center; width: 25%; }
        .kpis .label { display: block; font-size: 10px; color: #666; text-transform: uppercase; margin-bottom: 4px; }
        .kpis .value { display: block; font-size: 14px; font-weight: bold; color: #111; }
        table.data { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.data th, table.data td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
        table.data th { background-color: #f4f4f4; font-weight: bold; font-size: 11px; }
        .text-right { text-align: right; }
        .badge { padding: 2px 6px; border-radius: 4px; font-size: 10px; background: #eee; }
        .footer { margin-top: 30px; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer Statement</h1>
        <p><strong>Customer:</strong> {{ $customer->name ?? 'N/A' }}</p>
        <p><strong>Period:</strong> {{ $from ?? 'Start' }} to {{ $to ?? 'Now' }}</p>
        <p><strong>Date Generated:</strong> {{ now()->format('Y-m-d H:i') }}</p>
    </div>

    <table class="kpis">
        <tr>
            <td>
                <span class="label">Sales (Net)</span>
                <span class="value">{{ number_format($kpis['sales_total'], 2) }}</span>
            </td>
            <td>
                <span class="label">Paid by Customer</span>
                <span class="value">{{ number_format($kpis['paid_total'], 2) }}</span>
            </td>
            <td>
                <span class="label">Refunds</span>
                <span class="value">{{ number_format($kpis['refunds_total'], 2) }}</span>
            </td>
            <td>
                <span class="label">Balance</span>
                <span class="value">{{ number_format($kpis['balance'], 2) }}</span>
            </td>
        </tr>
    </table>

    <h3>Timeline</h3>
    <table class="data">
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Reference</th>
                <th>Method</th>
                <th class="text-right">Amount</th>
                <th class="text-right">Balance</th>
            </tr>
        </thead>
        <tbody>
            @forelse($events as $e)
                <tr>
                    <td>{{ $e['date']->format('Y-m-d') }}</td>
                    <td><span class="badge">{{ $e['type'] }}</span></td>
                    <td>
                        {{ $e['ref'] }}
                        @if(!empty($e['note']))
                            <br><small style="color:#666">{{ $e['note'] }}</small>
                        @endif
                    </td>
                    <td>{{ $e['method'] }}</td>
                    <td class="text-right">{{ number_format($e['amount'], 2) }}</td>
                    <td class="text-right">{{ number_format($e['balance'], 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px; color: #777;">No activity found for this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    @if($returns->count())
        <h3>Returns (Info)</h3>
        <table class="data">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Ref</th>
                    <th>Channel</th>
                    <th class="text-right">Returned Value</th>
                    <th class="text-right">Cash Refund</th>
                </tr>
            </thead>
            <tbody>
                @foreach($returns as $r)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($r->return_date)->format('Y-m-d') }}</td>
                        <td>Sale #{{ $r->sale_id }}</td>
                        <td>{{ strtoupper($r->payment_channel ?? '-') }}</td>
                        <td class="text-right">{{ number_format($r->total_amount, 2) }}</td>
                        <td class="text-right">{{ number_format($r->refund_amount, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by Nezerwa Plus
    </div>
</body>
</html>
