<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice #{{ $sale->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #333; font-size: 13px; }
        .container { width: 100%; margin: 0 auto; padding: 20px; }
        .header { display: flex; justify-content: space-between; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #1e293b; }
        .company-info, .customer-info { margin-bottom: 10px; }
        .info-table td { padding: 4px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
        th { background-color: #f3f4f6; }
        .total { font-weight: bold; background-color: #f9fafb; }
        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
<div class="container">

    {{-- Header --}}
    <div class="header">
        <div>
            <h1>INVOICE</h1>
            <p><strong>Invoice #:</strong> {{ $sale->id }}</p>
            <p><strong>Date:</strong> {{ $sale->sale_date }}</p>
        </div>
        <div style="text-align:right;">
            <h3>{{ config('app.name', 'Stock Manager') }}</h3>
            <p>Powered by Divva System</p>
        </div>
    </div>

    {{-- Customer Info --}}
    <div class="customer-info">
        <h4>Bill To:</h4>
        @if($sale->customer)
            <table class="info-table">
                <tr><td><strong>Name:</strong></td><td>{{ $sale->customer->name }}</td></tr>
                <tr><td><strong>Phone:</strong></td><td>{{ $sale->customer->phone ?? '-' }}</td></tr>
                <tr><td><strong>Email:</strong></td><td>{{ $sale->customer->email ?? '-' }}</td></tr>
            </table>
        @else
            <p>Walk-in Customer</p>
        @endif
    </div>

    {{-- Sale Details --}}
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th style="text-align:center;">Quantity</th>
                <th style="text-align:right;">Unit Price</th>
                <th style="text-align:right;">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sale->items as $item)
                <tr>
                    <td>{{ $item->product->name }}</td>
                    <td style="text-align:center;">{{ $item->quantity }}</td>
                    <td style="text-align:right;">{{ number_format($item->unit_price, 2) }}</td>
                    <td style="text-align:right;">{{ number_format($item->subtotal, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total">
                <td colspan="3" style="text-align:right;">Total:</td>
                <td style="text-align:right;">{{ number_format($sale->total_amount, 2) }}</td>
            </tr>
            <tr class="total">
                <td colspan="3" style="text-align:right;">Amount Paid:</td>
                <td style="text-align:right;">{{ number_format($sale->amount_paid ?? 0, 2) }}</td>
            </tr>
            <tr class="total">
                <td colspan="3" style="text-align:right;">Balance:</td>
                <td style="text-align:right; color:{{ $sale->balance > 0 ? 'red' : 'green' }};">
                    {{ number_format($sale->balance, 2) }}
                </td>
            </tr>
        </tfoot>
    </table>

    {{-- Notes --}}
    @if($sale->notes)
        <div style="margin-top:20px;">
            <strong>Notes:</strong>
            <p>{{ $sale->notes }}</p>
        </div>
    @endif

    {{-- Footer --}}
    <div class="footer">
        <p>Thank you for your business!</p>
        <p>Generated by {{ config('app.name') }} — {{ now()->format('d M Y, H:i') }}</p>
    </div>

</div>
</body>
</html>
