<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice #{{ $sale->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #333; }
        .container { width: 95%; margin: 0 auto; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #1e293b; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ccc; padding: 8px; }
        th { background-color: #f3f4f6; text-align: left; }
        .total-row { background-color: #f9fafb; font-weight: bold; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #777; }
    </style>
</head>
<body>
<div class="container">
    {{-- Header --}}
    <div class="header">
        <div>
            <h1>INVOICE</h1>
            <p><strong>Invoice #:</strong> {{ $sale->id }}</p>
            <p><strong>Date:</strong> {{ optional($sale->sale_date)->format('Y-m-d') }}</p>
        </div>
        <div style="text-align:right;">
            <h3>{{ config('app.name', 'Stock Manager') }}</h3>
            <p>Powered by Stock Management</p>
        </div>
    </div>

    {{-- Customer Info --}}
    <div style="margin-bottom:15px;">
        <h4>Bill To:</h4>
        @if($sale->customer)
            <p><strong>Name:</strong> {{ $sale->customer->name }}</p>
            <p><strong>Phone:</strong> {{ $sale->customer->phone ?? '-' }}</p>
            <p><strong>Email:</strong> {{ $sale->customer->email ?? '-' }}</p>
        @else
            <p>Walk-in Customer</p>
        @endif
    </div>

    {{-- Items --}}
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th style="text-align:center;">Qty</th>
                <th style="text-align:right;">Unit Price</th>
                <th style="text-align:right;">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sale->items as $item)
                <tr>
                    <td>{{ $item->product->name ?? 'N/A' }}</td>
                    <td style="text-align:center;">{{ $item->quantity }}</td>
                    <td style="text-align:right;">{{ number_format($item->unit_price, 2) }}</td>
                    <td style="text-align:right;">{{ number_format($item->subtotal, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="3" style="text-align:right;">Total:</td>
                <td style="text-align:right;">{{ number_format($sale->total_amount, 2) }}</td>
            </tr>
            <tr class="total-row">
                <td colspan="3" style="text-align:right;">Paid:</td>
                <td style="text-align:right;">{{ number_format($sale->amount_paid ?? 0, 2) }}</td>
            </tr>
            <tr class="total-row">
                <td colspan="3" style="text-align:right;">Balance:</td>
                <td style="text-align:right; color:{{ $sale->balance > 0 ? 'red' : 'green' }};">
                    {{ number_format($sale->balance, 2) }}
                </td>
            </tr>
        </tfoot>
    </table>

    {{-- Notes --}}
    @if($sale->notes)
        <div style="margin-top:20px;">
            <strong>Notes:</strong>
            <p>{{ $sale->notes }}</p>
        </div>
    @endif

    {{-- Footer --}}
    <div class="footer">
        <p>Thank you for your business!</p>
        <p>Generated by {{ config('app.name') }} — {{ now()->format('d M Y, H:i') }}</p>
    </div>
</div>
</body>
</html>
