<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Finance Report ({{ $start }} → {{ $end }})</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #222;
            font-size: 13px;
            line-height: 1.6;
            margin: 40px;
        }

        /* ---- Typography ---- */
        h1 {
            text-align: center;
            font-size: 20px;
            font-weight: 600;
            color: #111827;
            margin-bottom: 5px;
        }
        h2 {
            font-size: 15px;
            color: #374151;
            border-bottom: 1px solid #E5E7EB;
            padding-bottom: 4px;
            margin-top: 25px;
            margin-bottom: 10px;
        }
        p {
            text-align: center;
            font-size: 12px;
            color: #6B7280;
            margin-bottom: 25px;
        }

        /* ---- Tables ---- */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            margin-bottom: 30px;
        }
        th, td {
            border: 1px solid #E5E7EB;
            padding: 10px 12px;
            text-align: right;
        }
        td.label {
            text-align: left;
            font-weight: 600;
            color: #374151;
        }
        th {
            background-color: #F9FAFB;
            font-weight: 600;
            color: #374151;
        }
        tr:nth-child(even) {
            background-color: #FAFAFA;
        }

        /* ---- Totals and Colors ---- */
        .text-green { color: #059669; }
        .text-red { color: #DC2626; }
        .text-indigo { color: #4F46E5; }

        /* ---- Footer ---- */
        footer {
            text-align: center;
            font-size: 11px;
            color: #6B7280;
            border-top: 1px solid #E5E7EB;
            padding-top: 8px;
            margin-top: 30px;
        }
    </style>
</head>
<body>

    {{-- ===== HEADER ===== --}}
    <h1>Stock Manager</h1>
    <p>
        Finance Report<br>
        Period: {{ $start }} → {{ $end }}
    </p>

    {{-- ===== FINANCIAL SUMMARY TABLE ===== --}}
    <h2>Summary Overview</h2>
    <table>
        <tbody>
            <tr>
                <td class="label">Total Credits (In)</td>
                <td class="text-green">{{ number_format($credits, 2) }}</td>
            </tr>
            <tr>
                <td class="label">Total Debits (Out)</td>
                <td class="text-red">{{ number_format($debits, 2) }}</td>
            </tr>
            <tr>
                <td class="label">Net Balance</td>
                <td class="{{ $netBalance >= 0 ? 'text-green' : 'text-red' }}">
                    {{ number_format($netBalance, 2) }}
                </td>
            </tr>
            <tr>
                <td class="label">Total Profit</td>
                <td class="text-indigo">{{ number_format($totalProfit, 2) }}</td>
            </tr>
        </tbody>
    </table>

    {{-- ===== FOOTER ===== --}}
    <footer>
        Generated by <strong>Stock Manager</strong> |
        {{ now()->format('d M Y H:i') }} <br>
        Confidential financial report — internal use only.
    </footer>

</body>
</html>
